version: '3.8'

services:
  auth-db-postgres:
    image: postgres:16-alpine
    container_name: auth-db-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - id-app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  seven-id-oauth2:
    image: seven-id-oauth2:latest
    container_name: seven-id-oauth2
    depends_on:
      auth-db-postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - id-app-net
    environment:
      DATASOURCE_URL: jdbc:postgresql://auth-db-postgres:5432/auth_db

networks:
  id-app-net:
    driver: bridge

volumes:
  postgres_data: