version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: seven-id-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: seven-id-oauth2:latest
    container_name: seven-id-oauth2
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - app-net
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data: