server:
  port: 8082
spring:
  application:
    name: 'oauth2-resource-client-hybrid'
  security:
    oauth2:
      resourceserver:
        jwt:
          trusted-issuers:
            - 'https://accounts.google.com'
            - 'https://appleid.apple.com'
        opaquetoken:
          servers:
            - introspection-uri: ${OAUTH2_S1_OT_INTROSPECTION_URI:blank}
              client-id: ${OAUTH2_S1_OT_CLIENT_ID:blank}
              client-secret: ${OAUTH2_S1_OT_CLIENT_SECRET:blank}
              name: ${OAUTH2_S1_OT_NAME:blank}
      client:
        registration:
          google:
            provider: google
            client-id: ${OIDC_GOOGLE_CLIENT_ID:blank}
            client-secret: ${OIDC_GOOGLE_CLIENT_SECRET:blank}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: 'https://accounts.google.com'
  #          apple:
  #            client-id: google-client-id
  #            client-secret: google-client-secret

  flyway:
    enabled: true
    locations: classpath:db/migrations/default/postgresql
    schemas: [ public ]

  datasource:
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PG_PORT:5432}/auth_db
    hikari:
      auto-commit: false
springdoc:
  swagger-ui:
    path: /swagger