server:
  port: 8082
spring:
  application:
    name: 'oauth2'
  security:
    oauth2:
      # DOOR 1 & 2: Configuring the "Social Login" clients
      client:
        registration:
          google:
            client-id: ${OIDC_GOOGLE_CLIENT_ID:blank}
            client-secret: ${OIDC_GOOGLE_CLIENT_SECRET:blank}
            scope: openid, profile, email
          apple:
            client-id: ${OIDC_APPLE_CLIENT_ID:blank}
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope: openid, name, email
        provider:
          google:
            issuer-uri: 'https://accounts.google.com'
          apple:
            issuer-uri: 'https://appleid.apple.com'
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys

  flyway:
    enabled: true
    locations: classpath:db/migrations/default/postgresql
    schemas: [ public ]

  datasource:
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PG_PORT:5432}/auth_db
    hikari:
      auto-commit: false
springdoc:
  swagger-ui:
    path: /swagger

app:
  jwt:
    secret: ${JWT_SECRET_KEY:weak_jwt_signing_key00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}
    issuer: "http://localhost:8082"
    expiration-hrs: 1